FROM mhart/alpine-node:10
COPY . /www/
WORKDIR /www
ARG container_port=5000
ENV PORT=$container_port
EXPOSE $PORT

ARG AZURE_STORAGE_CONNECTION_STRING_DEV
ENV AZURE_STORAGE_CONNECTION_STRING_DEV=$AZURE_STORAGE_CONNECTION_STRING_DEV
RUN echo "AZURE_STORAGE_CONNECTION_STRING_DEV: $AZURE_STORAGE_CONNECTION_STRING_DEV"

ARG AZURE_STORAGE_ACCOUNT_DEV
ENV AZURE_STORAGE_ACCOUNT_DEV=$AZURE_STORAGE_ACCOUNT_DEV
RUN echo "AZURE_STORAGE_CONNECTION_STRING_DEV: $AZURE_STORAGE_ACCOUNT_DEV"

ARG AZURE_STORAGE_ACCESS_KEY_DEV
ENV AZURE_STORAGE_ACCESS_KEY_DEV=$AZURE_STORAGE_ACCESS_KEY_DEV
RUN echo "AZURE_STORAGE_ACCESS_KEY_DEV: $AZURE_STORAGE_ACCESS_KEY_DEV"

ARG API_USERNAME
ENV API_USERNAME=$API_USERNAME
RUN echo "API_USERNAME: $API_USERNAME"

ARG API_PASSWORD
ENV API_PASSWORD=$API_PASSWORD
RUN echo "API_PASSWORD: $API_PASSWORD"

RUN yarn install
CMD yarn start